// <auto-generated />
using System;
using pzellhorn.Core.State.Base.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pzellhorn.Core.State.Base.DBContext;

#nullable disable

namespace FlutterMessaging.State.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20250928071838_init_tables")]
    partial class init_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ChatRoom", b =>
                {
                    b.Property<Guid>("ChatRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ChatRoomId")
                        .HasName("pk_chat_rooms");

                    b.ToTable("chat_rooms", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ChatRoomMember", b =>
                {
                    b.Property<Guid>("ChatRoomMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chat_room_member_id");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("ChatRoomMemberId")
                        .HasName("pk_chat_room_members");

                    b.HasIndex("ChatRoomId")
                        .HasDatabaseName("ix_chat_room_members_chat_room_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_chat_room_members_profile_id");

                    b.ToTable("chat_room_members", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ChatRoomMessage", b =>
                {
                    b.Property<Guid>("ChatRoomMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chat_room_message_id");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("ChatRoomMessageId")
                        .HasName("pk_chat_room_messages");

                    b.HasIndex("ChatRoomId")
                        .HasDatabaseName("ix_chat_room_messages_chat_room_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_chat_room_messages_profile_id");

                    b.ToTable("chat_room_messages", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardAnswer", b =>
                {
                    b.Property<Guid>("FlashCardAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("flash_card_answer_id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FlashCardSetTemplateItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("flash_card_set_template_item_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("FlashCardAnswerId")
                        .HasName("pk_flash_card_answers");

                    b.HasIndex("FlashCardSetTemplateItemId")
                        .HasDatabaseName("ix_flash_card_answers_flash_card_set_template_item_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_flash_card_answers_profile_id");

                    b.ToTable("flash_card_answers", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardSetTemplate", b =>
                {
                    b.Property<Guid>("FlashCardSetTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("flash_card_set_template_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FlashCardSetName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flash_card_set_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("FlashCardSetTemplateId")
                        .HasName("pk_flash_card_set_templates");

                    b.ToTable("flash_card_set_templates", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardSetTemplateItem", b =>
                {
                    b.Property<Guid>("FlashCardSetTemplateItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("flash_card_set_template_item_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FlashCardSetTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("flash_card_set_template_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.HasKey("FlashCardSetTemplateItemId")
                        .HasName("pk_flash_card_set_template_items");

                    b.HasIndex("FlashCardSetTemplateId")
                        .HasDatabaseName("ix_flash_card_set_template_items_flash_card_set_template_id");

                    b.ToTable("flash_card_set_template_items", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.LanguageTranslation", b =>
                {
                    b.Property<Guid>("LanguageTranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("language_translation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FromLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_language_id");

                    b.Property<string>("FromLanguageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_language_text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ToLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_language_id");

                    b.Property<string>("ToLanguageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_language_text");

                    b.HasKey("LanguageTranslationId")
                        .HasName("pk_language_translations");

                    b.ToTable("language_translations", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.LanguageWordFrequency", b =>
                {
                    b.Property<Guid>("LanguageWordFrequencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("language_word_frequency_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("FrequencyRank")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_rank");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<Guid>("LanguageTranslationId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_translation_id");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("LanguageWordFrequencyId")
                        .HasName("pk_language_word_frequencies");

                    b.HasIndex("LanguageTranslationId")
                        .HasDatabaseName("ix_language_word_frequencies_language_translation_id");

                    b.ToTable("language_word_frequencies", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_name");

                    b.HasKey("ProfileId")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ProfileSetting", b =>
                {
                    b.Property<Guid>("ProfileSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_setting_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("ProfileSettingId")
                        .HasName("pk_profile_settings");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_profile_settings_profile_id");

                    b.ToTable("profile_settings", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ProfileSettingOption", b =>
                {
                    b.Property<Guid>("ProfileSettingOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_setting_option_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_key");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_value");

                    b.Property<Guid>("ProfileSettingId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_setting_id");

                    b.HasKey("ProfileSettingOptionId")
                        .HasName("pk_profile_setting_options");

                    b.HasIndex("ProfileSettingId")
                        .HasDatabaseName("ix_profile_setting_options_profile_setting_id");

                    b.ToTable("profile_setting_options", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ChatRoomMember", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.ChatRoom", "ChatRoom")
                        .WithMany("ChatRoomMembers")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_members_chat_rooms_chat_room_id");

                    b.HasOne("FlutterMessaging.State.Data.Entities.Profile", "Profile")
                        .WithMany("ChatRoomMembers")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_members_profile_profile_id");

                    b.Navigation("ChatRoom");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ChatRoomMessage", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.ChatRoom", "ChatRoom")
                        .WithMany("ChatRoomMessages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_messages_chat_rooms_chat_room_id");

                    b.HasOne("FlutterMessaging.State.Data.Entities.Profile", "Profile")
                        .WithMany("ChatRoomMessages")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_messages_profile_profile_id");

                    b.Navigation("ChatRoom");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardAnswer", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.FlashCardSetTemplateItem", "FlashCardSetTemplateItem")
                        .WithMany("FlashCardAnswers")
                        .HasForeignKey("FlashCardSetTemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flash_card_answers_flash_card_set_template_item_flash_card_");

                    b.HasOne("FlutterMessaging.State.Data.Entities.Profile", "Profile")
                        .WithMany("FlashCardAnswers")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flash_card_answers_profile_profile_id");

                    b.Navigation("FlashCardSetTemplateItem");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardSetTemplateItem", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.FlashCardSetTemplate", "FlashCardSetTemplate")
                        .WithMany("FlashCardSetTemplateItems")
                        .HasForeignKey("FlashCardSetTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flash_card_set_template_items_flash_card_set_templates_flas");

                    b.Navigation("FlashCardSetTemplate");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.LanguageWordFrequency", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.LanguageTranslation", "LanguageTranslation")
                        .WithMany("LanguageWordFrequencies")
                        .HasForeignKey("LanguageTranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_language_word_frequencies_language_translations_language_tr");

                    b.Navigation("LanguageTranslation");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ProfileSetting", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.Profile", "Profile")
                        .WithMany("ProfileSettings")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_settings_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ProfileSettingOption", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.ProfileSetting", "ProfileSetting")
                        .WithMany("ProfileSettingOptions")
                        .HasForeignKey("ProfileSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_setting_options_profile_settings_profile_setting_id");

                    b.Navigation("ProfileSetting");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ChatRoom", b =>
                {
                    b.Navigation("ChatRoomMembers");

                    b.Navigation("ChatRoomMessages");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardSetTemplate", b =>
                {
                    b.Navigation("FlashCardSetTemplateItems");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardSetTemplateItem", b =>
                {
                    b.Navigation("FlashCardAnswers");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.LanguageTranslation", b =>
                {
                    b.Navigation("LanguageWordFrequencies");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.Profile", b =>
                {
                    b.Navigation("ChatRoomMembers");

                    b.Navigation("ChatRoomMessages");

                    b.Navigation("FlashCardAnswers");

                    b.Navigation("ProfileSettings");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ProfileSetting", b =>
                {
                    b.Navigation("ProfileSettingOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
