// <auto-generated />
using System;
using FlutterMessaging.State.Base.dbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlutterMessaging.State.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    [Migration("20251008031202_addTemplateType")]
    partial class addTemplateType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ChatRoom", b =>
                {
                    b.Property<Guid>("ChatRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ChatRoomId")
                        .HasName("pk_chat_rooms");

                    b.ToTable("chat_rooms", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ChatRoomMember", b =>
                {
                    b.Property<Guid>("ChatRoomMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chat_room_member_id");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("ChatRoomMemberId")
                        .HasName("pk_chat_room_members");

                    b.HasIndex("ChatRoomId")
                        .HasDatabaseName("ix_chat_room_members_chat_room_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_chat_room_members_profile_id");

                    b.ToTable("chat_room_members", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ChatRoomMessage", b =>
                {
                    b.Property<Guid>("ChatRoomMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chat_room_message_id");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("ChatRoomMessageId")
                        .HasName("pk_chat_room_messages");

                    b.HasIndex("ChatRoomId")
                        .HasDatabaseName("ix_chat_room_messages_chat_room_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_chat_room_messages_profile_id");

                    b.ToTable("chat_room_messages", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ExternalIdentity", b =>
                {
                    b.Property<Guid>("ExternalIdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("external_identity_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("ExternalIdentityId")
                        .HasName("pk_external_identities");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_external_identities_profile_id");

                    b.ToTable("external_identities", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardAnswer", b =>
                {
                    b.Property<Guid>("FlashCardAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("flash_card_answer_id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FlashCardSetTemplateItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("flash_card_set_template_item_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("FlashCardAnswerId")
                        .HasName("pk_flash_card_answers");

                    b.HasIndex("FlashCardSetTemplateItemId")
                        .HasDatabaseName("ix_flash_card_answers_flash_card_set_template_item_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_flash_card_answers_profile_id");

                    b.ToTable("flash_card_answers", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardSetTemplate", b =>
                {
                    b.Property<Guid>("FlashCardSetTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("flash_card_set_template_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FlashCardSetName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flash_card_set_name");

                    b.Property<int>("FlashCardType")
                        .HasColumnType("integer")
                        .HasColumnName("flash_card_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("FlashCardSetTemplateId")
                        .HasName("pk_flash_card_set_templates");

                    b.ToTable("flash_card_set_templates", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardSetTemplateItem", b =>
                {
                    b.Property<Guid>("FlashCardSetTemplateItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("flash_card_set_template_item_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FlashCardSetTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("flash_card_set_template_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.HasKey("FlashCardSetTemplateItemId")
                        .HasName("pk_flash_card_set_template_items");

                    b.HasIndex("FlashCardSetTemplateId")
                        .HasDatabaseName("ix_flash_card_set_template_items_flash_card_set_template_id");

                    b.ToTable("flash_card_set_template_items", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardSetTemplateItemOption", b =>
                {
                    b.Property<Guid>("FlashCardSetTemplateItemOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("flash_card_set_template_item_option_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FlashCardSetTemplateItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("flash_card_set_template_item_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_key");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_value");

                    b.HasKey("FlashCardSetTemplateItemOptionId")
                        .HasName("pk_flash_card_set_template_item_options");

                    b.HasIndex("FlashCardSetTemplateItemId")
                        .HasDatabaseName("ix_flash_card_set_template_item_options_flash_card_set_templat");

                    b.ToTable("flash_card_set_template_item_options", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.JwtKey", b =>
                {
                    b.Property<Guid>("JwtKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("jwt_key_id");

                    b.Property<string>("Alg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alg");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("KeyVaultKeyId")
                        .HasColumnType("text")
                        .HasColumnName("key_vault_key_id");

                    b.Property<string>("Kid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kid");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PublicKeyPem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key_pem");

                    b.HasKey("JwtKeyId")
                        .HasName("pk_jwt_keys");

                    b.ToTable("jwt_keys", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("LanguageId")
                        .HasName("pk_languages");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.LanguageTranslation", b =>
                {
                    b.Property<Guid>("LanguageTranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("language_translation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FromLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_language_id");

                    b.Property<string>("FromLanguageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_language_text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("LangaugeLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("langauge_language_id");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ToLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_language_id");

                    b.Property<string>("ToLanguageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_language_text");

                    b.HasKey("LanguageTranslationId")
                        .HasName("pk_language_translations");

                    b.HasIndex("LangaugeLanguageId")
                        .HasDatabaseName("ix_language_translations_langauge_language_id");

                    b.ToTable("language_translations", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.LanguageWordFrequency", b =>
                {
                    b.Property<Guid>("LanguageWordFrequencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("language_word_frequency_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("FrequencyRank")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_rank");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<Guid>("LanguageTranslationId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_translation_id");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("LanguageWordFrequencyId")
                        .HasName("pk_language_word_frequencies");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_language_word_frequencies_language_id");

                    b.ToTable("language_word_frequencies", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_name");

                    b.HasKey("ProfileId")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ProfileSetting", b =>
                {
                    b.Property<Guid>("ProfileSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_setting_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("ProfileSettingId")
                        .HasName("pk_profile_settings");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_profile_settings_profile_id");

                    b.ToTable("profile_settings", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ProfileSettingOption", b =>
                {
                    b.Property<Guid>("ProfileSettingOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_setting_option_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_key");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_value");

                    b.Property<Guid>("ProfileSettingId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_setting_id");

                    b.HasKey("ProfileSettingOptionId")
                        .HasName("pk_profile_setting_options");

                    b.HasIndex("ProfileSettingId")
                        .HasDatabaseName("ix_profile_setting_options_profile_setting_id");

                    b.ToTable("profile_setting_options", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<string>("TokenSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_salt");

                    b.HasKey("RefreshTokenId")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedById")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_refresh_tokens_session_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("text")
                        .HasColumnName("device_info");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("SessionId")
                        .HasName("pk_sessions");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_sessions_profile_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ChatRoomMember", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.ChatRoom", "ChatRoom")
                        .WithMany("ChatRoomMembers")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_members_chat_rooms_chat_room_id");

                    b.HasOne("FlutterMessaging.State.Data.Entities.Profile", "Profile")
                        .WithMany("ChatRoomMembers")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_members_profile_profile_id");

                    b.Navigation("ChatRoom");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ChatRoomMessage", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.ChatRoom", "ChatRoom")
                        .WithMany("ChatRoomMessages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_messages_chat_rooms_chat_room_id");

                    b.HasOne("FlutterMessaging.State.Data.Entities.Profile", "Profile")
                        .WithMany("ChatRoomMessages")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_messages_profile_profile_id");

                    b.Navigation("ChatRoom");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ExternalIdentity", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.Profile", "Profile")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_identities_profile_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardAnswer", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.FlashCardSetTemplateItem", "FlashCardSetTemplateItem")
                        .WithMany("FlashCardAnswers")
                        .HasForeignKey("FlashCardSetTemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flash_card_answers_flash_card_set_template_item_flash_card_");

                    b.HasOne("FlutterMessaging.State.Data.Entities.Profile", "Profile")
                        .WithMany("FlashCardAnswers")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flash_card_answers_profile_profile_id");

                    b.Navigation("FlashCardSetTemplateItem");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardSetTemplateItem", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.FlashCardSetTemplate", "FlashCardSetTemplate")
                        .WithMany("FlashCardSetTemplateItems")
                        .HasForeignKey("FlashCardSetTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flash_card_set_template_items_flash_card_set_templates_flas");

                    b.Navigation("FlashCardSetTemplate");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardSetTemplateItemOption", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.FlashCardSetTemplateItem", "FlashCardSetTemplateItem")
                        .WithMany("FlashCardSetTemplateItemOptions")
                        .HasForeignKey("FlashCardSetTemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flash_card_set_template_item_options_flash_card_set_templat");

                    b.Navigation("FlashCardSetTemplateItem");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.LanguageTranslation", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.Language", "Langauge")
                        .WithMany()
                        .HasForeignKey("LangaugeLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_language_translations_languages_langauge_language_id");

                    b.Navigation("Langauge");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.LanguageWordFrequency", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.Language", "Language")
                        .WithMany("LanguageWordFrequencies")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_language_word_frequencies_languages_language_id");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ProfileSetting", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.Profile", "Profile")
                        .WithMany("ProfileSettings")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_settings_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ProfileSettingOption", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.ProfileSetting", "ProfileSetting")
                        .WithMany("ProfileSettingOptions")
                        .HasForeignKey("ProfileSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_setting_options_profile_settings_profile_setting_id");

                    b.Navigation("ProfileSetting");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.RefreshToken", "ReplacedBy")
                        .WithMany()
                        .HasForeignKey("ReplacedById")
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_id");

                    b.HasOne("FlutterMessaging.State.Data.Entities.Session", "Session")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_session_session_id");

                    b.Navigation("ReplacedBy");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.Session", b =>
                {
                    b.HasOne("FlutterMessaging.State.Data.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ChatRoom", b =>
                {
                    b.Navigation("ChatRoomMembers");

                    b.Navigation("ChatRoomMessages");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardSetTemplate", b =>
                {
                    b.Navigation("FlashCardSetTemplateItems");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.FlashCardSetTemplateItem", b =>
                {
                    b.Navigation("FlashCardAnswers");

                    b.Navigation("FlashCardSetTemplateItemOptions");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.Language", b =>
                {
                    b.Navigation("LanguageWordFrequencies");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.Profile", b =>
                {
                    b.Navigation("ChatRoomMembers");

                    b.Navigation("ChatRoomMessages");

                    b.Navigation("ExternalIdentities");

                    b.Navigation("FlashCardAnswers");

                    b.Navigation("ProfileSettings");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.ProfileSetting", b =>
                {
                    b.Navigation("ProfileSettingOptions");
                });

            modelBuilder.Entity("FlutterMessaging.State.Data.Entities.Session", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
