substitutions:
  _REGION: "europe-west6"
  _REPO: "messaging-containers"
  _SERVICE: "messaging-api"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
#Make sure we got perms
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - services
    - enable
    - run.googleapis.com
    - sqladmin.googleapis.com
    - artifactregistry.googleapis.com
    - secretmanager.googleapis.com
    - --project=$PROJECT_ID
    - --quiet

# Checkout Core repo
- name: 'gcr.io/cloud-builders/git'
  entrypoint: bash
  args:
    - -lc
    - |
      set -euxo pipefail 
      ls -la .git || echo "No .git directory found"
      git submodule sync --recursive
      git submodule update --init
      find Core -maxdepth 3 -name '*.csproj' -print

# Build image 
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -f
    - src/FlutterMessaging.API/Dockerfile
    - -t
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA'
    - .
     
# Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA'

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_SERVICE}
    - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA'
    - '--region=${_REGION}'
    - '--platform=managed'
    - '--allow-unauthenticated'
    # attach Cloud SQL (instance connection name)
    - '--add-cloudsql-instances=messaginglangugetranslation:europe-west6:messagingdb'
    # secrets (repeatable flag is OK)
    - '--set-secrets=ConnectionStrings__Default=ConnectionStrings__Default:latest'
    - '--set-secrets=Jwt__SigningKey=Jwt__SigningKey:latest'
    - '--set-secrets=RefreshToken__Pepper=RefreshToken__Pepper:latest'
    - '--set-secrets=GoogleAPIKey=GoogleAPIKey:latest'
    # .NET 8 container port
    - '--set-env-vars=ASPNETCORE_HTTP_PORTS=8080'
    - '--quiet'  

images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA'
